# Generated by Django 5.0.6 on 2024-07-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                ("shortened_id", models.CharField(max_length=10, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("click_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name="url",
            constraint=models.UniqueConstraint(
                fields=("shortened_id",), name="unique_shortened_id"
            ),
        ),
    ]
